package com.sample
 
import com.sample.DroolsTest.Question;
import com.sample.DroolsTest.Fact;

rule "pregnant"
    when
    then
        System.out.println( "pregnant" );
        
        Question q=new Question("Has a major character been pregnant during the show?"); 
        q.addAns("Yes");
        q.addAns("No");
        q.addAns("No, but she thought she was");
        q.addAns("What do you mean, 'during'?");
        q.showQuestion();
        
        insert(new Fact("pregnant", q.getUserAnswer())); 
end

rule "black"
    when
        f: Fact(name.equals("pregnant"), answer.equals("Yes"))
    then
        System.out.println( "black" );
        
        Question q=new Question("Are there any black people?"); 
        q.addAns("Yes");
        q.addAns("No. These characters are so white, they're frightened of the Irish");
        q.addAns("Barely");
        q.showQuestion();
        
        insert(new Fact("black", q.getUserAnswer()));
end

rule "DowntonAbbey"
    when
        f: Fact(name.equals("black"), answer.equals("No. These characters are so white, they're frightened of the Irish"))
    then     
        new Fact("DowntonAbbey");
end

rule "zombie"
    when
        f: Fact(name.equals("black"), answer.equals("Yes"))
    then
        System.out.println( "zombie" );
        
        Question q=new Question("Have there been zombies?"); 
        q.addAns("Yes");
        q.addAns("No");
        q.addAns("Only if you count dazed employees");
        q.showQuestion();
        
        insert(new Fact("zombie", q.getUserAnswer()));
end

rule "TheOffice"
    when
        f: Fact(name.equals("zombie"), answer.equals("Only if you count dazed employees"))
    then     
        new Fact("TheOffice");
end

rule "realZombie"
    when
        f: Fact(name.equals("zombie"), answer.equals("Yes"))
    then
        System.out.println( "realZombie" );
        
        Question q=new Question("Real zombies?"); 
        q.addAns("Uh,yes, hello, only ALL THE TIME");
        q.addAns("No");
        q.showQuestion();
        
        insert(new Fact("realZombie", q.getUserAnswer()));
end

rule "WalkingDead"
    when
        f: Fact(name.equals("realZombie"), answer.equals("Uh,yes, hello, only ALL THE TIME"))
    then 
        new Fact("WalkingDead");
end

rule "Community"
    when
        f: Fact(name.equals("realZombie"), answer.equals("No"))
    then  
        new Fact("Community");
end

rule "getShot"
    when
        f: Fact(name.equals("zombie"), answer.equals("No"))
    then
        Question q=new Question("Roughly how often do people get shot?"); 
        q.addAns("Every so often");
        q.addAns("Never");
        q.addAns("Literally all the time");
        q.showQuestion();
        
        insert(new Fact("getShot", q.getUserAnswer()));
end

rule "BoardwalkEmpire"
    when
        f: Fact(name.equals("getShot"), answer.equals("Every so often"))
    then 
        new Fact("BoardwalkEmpire");
end

rule "sing"
    when
        f: Fact(name.equals("getShot"), answer.equals("Never"))
    then
        Question q=new Question("Do the characters sing a lot?"); 
        q.addAns("Big time");
        q.addAns("No, thank God");
        q.showQuestion();
        
        insert(new Fact("sing", q.getUserAnswer()));
end

rule "songs"
    when
        f: Fact(name.equals("sing"), answer.equals("Big time"))
    then
        Question q=new Question("Covers or original songs?"); 
        q.addAns("Originals. Horrible, horrible originals.");
        q.addAns("Covers. Horrible, horrible Covers.");
        q.showQuestion();
        
        insert(new Fact("songs", q.getUserAnswer()));
end

rule "Smash"
    when
        f: Fact(name.equals("songs"), answer.equals("Originals. Horrible, horrible originals."))
    then 
        new Fact("Smash");
end

rule "Glee"
    when
        f: Fact(name.equals("songs"), answer.equals("Covers. Horrible, horrible Covers."))
    then 
        new Fact("Glee");
end

rule "Parenthood"
    when
        f: Fact(name.equals("sing"), answer.equals("No, thank God"))
    then 
        new Fact("Parenthood");
end

rule "Justified"
    when
        f: Fact(name.equals("getShot"), answer.equals("Literally all the time"))
    then 
        new Fact("Justified");
end

rule "cellPhones"
    when
        f: Fact(name.equals("black"), answer.equals("Barely"))
    then
        
        Question q=new Question("Do the characters use cell phones?"); 
        q.addAns("Yes");
        q.addAns("No");
        q.showQuestion();
        
        insert(new Fact("cellPhones", q.getUserAnswer()));
end

rule "sports"
    when
        f: Fact(name.equals("cellPhones"), answer.equals("Yes"))
    then
        
        Question q=new Question("Do they play sports?"); 
        q.addAns("Yes");
        q.addAns("No");
        q.showQuestion();
        
        insert(new Fact("sports", q.getUserAnswer()));
end

rule "haunted"
    when
        f: Fact(name.equals("sports"), answer.equals("No"))
    then
        
        Question q=new Question("Is stuff haunted?"); 
        q.addAns("Yes, almost everything");
        q.addAns("No, nothing");
        q.addAns("Only Walt's eyes, with the absolute corruption of his innermost soul");
        q.showQuestion();
        
        insert(new Fact("haunted", q.getUserAnswer()));
end

rule "mother"
    when
        f: Fact(name.equals("haunted"), answer.equals("No, nothing"))
    then
        
        Question q=new Question("Do we know who everyone's mother is?"); 
        q.addAns("Yeah...? That's a weird question.");
        q.addAns("No, and frankly it started getting ridiculous four seasons ago. Come on, writers, just tell us.");
        q.showQuestion();
        
        insert(new Fact("mother", q.getUserAnswer()));
end

rule "ModernFamily"
    when
        f: Fact(name.equals("mother"), answer.equals("Yeah...? That's a weird question."))
    then
        new Fact("ModernFamily");
end

rule "HowIMeetYourMother"
    when
        f: Fact(name.equals("mother"), answer.equals("No, and frankly it started getting ridiculous four seasons ago. Come on, writers, just tell us."))
    then
        new Fact("HowIMeetYourMother");
end

rule "AmericanHorrorStory"
    when
        f: Fact(name.equals("haunted"), answer.equals("Yes, almost everything"))
    then
        new Fact("AmericanHorrorStory");
end

rule "BreakingBad"
    when
        f: Fact(name.equals("haunted"), answer.equals("Only Walt's eyes, with the absolute corruption of his innermost soul"))
    then
        new Fact("BreakingBad");
end

rule "kindSports"
    when
        f: Fact(name.equals("sports"), answer.equals("Yes"))
    then
        
        Question q=new Question("In the world of Queen, are these sports real life or are the just fantasy?"); 
        q.addAns("Fantasy");
        q.addAns("Real. 'I play real sports, not try to be the best at exercisings'");
        q.showQuestion();
        
        insert(new Fact("kindSports", q.getUserAnswer()));
end

rule "TheLeague"
    when
        f: Fact(name.equals("kindSports"), answer.equals("Fantasy"))
    then
        new Fact("TheLeague");
end

rule "Eastbound&Down"
    when
        f: Fact(name.equals("kindSports"), answer.equals("Real. 'I play real sports, not try to be the best at exercisings'"))
    then
        new Fact("Eastbound&Down");
end

rule "cars"
    when
        f: Fact(name.equals("cellPhones"), answer.equals("No"))
    then
        
        Question q=new Question("But they at least have cars, right?"); 
        q.addAns("Yes. Cars. Cars as luxurious as the woman you can never have.");
        q.addAns("Who needs a car when you can ride DEAD HORSES?");
        q.showQuestion();
        
        insert(new Fact("cars", q.getUserAnswer()));
end

rule "MadMen"
    when
        f: Fact(name.equals("cars"), answer.equals("Yes. Cars. Cars as luxurious as the woman you can never have."))
    then
        new Fact("MadMen");
end

rule "GameOfThrones"
    when
        f: Fact(name.equals("cars"), answer.equals("Who needs a car when you can ride DEAD HORSES?"))
    then
        new Fact("GameOfThrones");
end

rule "kids"
    when
        f: Fact(name.equals("pregnant"), answer.equals("No"))
    then
    
        Question q=new Question("Are there still kids on the show, thought?"); 
        q.addAns("Yes");
        q.addAns("No");
        q.showQuestion();
        
        insert(new Fact("kids",q.getUserAnswer()));
end

rule "northeast"
    when
        f: Fact(name.equals("kids"), answer.equals("Yes"))
    then
    
        Question q=new Question("Is the show set in the Northeast?"); 
        q.addAns("Yes");
        q.addAns("No");
        q.showQuestion();
        
        insert(new Fact("northeast",q.getUserAnswer()));
end

rule "queen"
    when
        f: Fact(name.equals("northeast"), answer.equals("Yes"))
    then
    
        Question q=new Question("Is there an evil queen?"); 
        q.addAns("Yes");
        q.addAns("Only if you count an ex-wife, amirite???");
        q.addAns("No");
        q.showQuestion();
        
        insert(new Fact("queen",q.getUserAnswer()));
end

rule "Once"
    when
        f: Fact(name.equals("queen"), answer.equals("Yes"))
    then
        new Fact("Once");
end

rule "Louie"
    when
        f: Fact(name.equals("queen"), answer.equals("Only if you count an ex-wife, amirite???"))
    then
        new Fact("Louie");
end

rule "Bob'sBurgers"
    when
        f: Fact(name.equals("queen"), answer.equals("No"))
    then
        new Fact("Bob'sBurgers");
end

rule "legitimatePlotline"
    when
        f: Fact(name.equals("northeast"), answer.equals("No"))
    then
    
        Question q=new Question("Could diaper changing be a legitimate plotline?"); 
        q.addAns("Unfortunately, yes");
        q.addAns("No");
        q.showQuestion();
        
        insert(new Fact("legitimatePlotline",q.getUserAnswer()));
end

rule "money"
    when
        f: Fact(name.equals("legitimatePlotline"), answer.equals("Unfortunately, yes"))
    then
    
        Question q=new Question("Are the characters rich or poor?"); 
        q.addAns("Rich enough to be best friends with basically Oprah");
        q.addAns("Poor enough to be best friends with a roller skating homeless dude");
        q.showQuestion();
        
        insert(new Fact("money",q.getUserAnswer()));
end

rule "UpAllNight"
    when
        f: Fact(name.equals("money"), answer.equals("Rich enough to be best friends with basically Oprah"))
    then
        new Fact("UpAllNight");
end

rule "RaisingHope"
    when
        f: Fact(name.equals("money"), answer.equals("Poor enough to be best friends with a roller skating homeless dude"))
    then
        new Fact("RaisingHope");
end

rule "Nashville"
    when
        f: Fact(name.equals("legitimatePlotline"), answer.equals("No"))
    then
        new Fact("Nashville");
end

rule "work"
    when
        f: Fact(name.equals("kids"), answer.equals("No"))
    then
    
        Question q=new Question("Do the characters work for some kind of goverment agency?"); 
        q.addAns("Yes");
        q.addAns("No");
        q.showQuestion();
        
        insert(new Fact("work",q.getUserAnswer()));
end

rule "SPYagency"
    when
        f: Fact(name.equals("work"), answer.equals("Yes"))
    then
    
        Question q=new Question("Do the characters work for some kind of goverment agency?"); 
        q.addAns("Danger zone!");
        q.addAns("No");
        q.addAns("I'm not at liberty to disclose that. Unless we're sleeping together.");
        q.showQuestion();
        
        insert(new Fact("SPYagency",q.getUserAnswer()));
end

rule "ParksAndRecreation"
    when
        f: Fact(name.equals("SPYagency"), answer.equals("No"))
    then
        new Fact("ParksAndRecreation");
end

rule "Homeland"
    when
        f: Fact(name.equals("SPYagency"), answer.equals("I'm not at liberty to disclose that. Unless we're sleeping together."))
    then
        new Fact("Homeland");
end

rule "Archer"
    when
        f: Fact(name.equals("SPYagency"), answer.equals("Danger zone!"))
    then
        new Fact("Archer");
end

rule "apartment"
    when
        f: Fact(name.equals("work"), answer.equals("No"))
    then
    
        Question q=new Question("Do the characters own apartments they definitely can't afford?"); 
        q.addAns("WHO HAS A LOFT LIKE THAT ON A BARISTA'S SALARY?");
        q.addAns("Nope");
        q.showQuestion();
        
        insert(new Fact("apartment",q.getUserAnswer()));
end

rule "cupcakes"
    when
        f: Fact(name.equals("apartment"), answer.equals("WHO HAS A LOFT LIKE THAT ON A BARISTA'S SALARY?"))
    then
    
        Question q=new Question("3 words: Are there cupcakes?"); 
        q.addAns("You know it");
        q.addAns("Not unless you count James Van Der Beek");
        q.addAns("No but that would be ah-MAH-zing");
        q.showQuestion();
        
        insert(new Fact("cupcakes",q.getUserAnswer()));
end

rule "2BrokeGirls"
    when
        f: Fact(name.equals("cupcakes"), answer.equals("You know it"))
    then
        new Fact("2BrokeGirls");
end

rule "Apt23"
    when
        f: Fact(name.equals("cupcakes"), answer.equals("Not unless you count James Van Der Beek"))
    then
        new Fact("Apt23");
end

rule "HappyEnding"
    when
        f: Fact(name.equals("cupcakes"), answer.equals("No but that would be ah-MAH-zing"))
    then
        new Fact("HappyEnding");
end

rule "sketchComedy"
    when
        f: Fact(name.equals("apartment"), answer.equals("Nope"))
    then
    
        Question q=new Question("Okay, so we must be talking sketch comedy."); 
        q.addAns("Nailed it");
        q.addAns("No, were not, dummy");
        q.showQuestion();
        
        insert(new Fact("sketchComedy",q.getUserAnswer()));
end

rule "hipsters"
    when
        f: Fact(name.equals("sketchComedy"), answer.equals("Nailed it"))
    then
    
        Question q=new Question("Sketch comedy about hipsters?"); 
        q.addAns("Yes, but I liked it before it was on Netflix");
        q.addAns("No");
        q.showQuestion();
        
        insert(new Fact("hipsters",q.getUserAnswer()));
end

rule "Portlandia"
    when
        f: Fact(name.equals("hipsters"), answer.equals("Yes, but I liked it before it was on Netflix"))
    then
        new Fact("Portlandia");
end

rule "Key&Peele"
    when
        f: Fact(name.equals("hipsters"), answer.equals("No"))
    then
        new Fact("Key&Peele");
end

rule "weed"
    when
        f: Fact(name.equals("sketchComedy"), answer.equals("No, were not, dummy"))
    then
    
        Question q=new Question("Huh. Uh...is there weed?"); 
        q.addAns("Yeah, they shmeoooke a bewrl");
        q.addAns("No");
        q.showQuestion();
        
        insert(new Fact("weed",q.getUserAnswer()));
end

rule "Workaholics"
    when
        f: Fact(name.equals("weed"), answer.equals("Yeah, they shmeoooke a bewrl"))
    then
        new Fact("Workaholics");
end

rule "Grimm"
    when
        f: Fact(name.equals("weed"), answer.equals("No"))
    then
        new Fact("Grimm");
end

rule "happy"
    when
        f: Fact(name.equals("pregnant"), answer.equals("No, but she thought she was"))
    then
    
    	Question q=new Question("Was she happy about it?"); 
        q.addAns("No");
        q.addAns("So happy she lizzed her parents.");
        q.showQuestion();
        
        insert(new Fact("happy",q.getUserAnswer()));
end

rule "girl"
    when
        f: Fact(name.equals("happy"), answer.equals("No"))
    then
    
    	Question q=new Question("Because she's only a girl right?"); 
        q.addAns("Yes");
        q.addAns("No");
        q.showQuestion();
        
        insert(new Fact("girl",q.getUserAnswer()));
end

rule "girlAdorkable"
    when
        f: Fact(name.equals("girl"), answer.equals("Yes"))
    then
    
    	Question q=new Question("A girl who's adorkable?"); 
        q.addAns("Are you happy now commercials? We're using your dumb made-up world.");
        q.addAns("No");
        q.showQuestion();
        
        insert(new Fact("girlAdorkable",q.getUserAnswer()));
end

rule "NewGirl"
    when
        f: Fact(name.equals("girlAdorkable"), answer.equals("Are you happy now commercials? We're using your dumb made-up world."))
    then
        new Fact("NewGirl");
end

rule "Girls"
    when
        f: Fact(name.equals("girlAdorkable"), answer.equals("No"))
    then
        new Fact("Girls");
end

rule "Veep"
    when
        f: Fact(name.equals("girl"), answer.equals("No"))
    then
        new Fact("Veep");
end

rule "30Rock"
    when
        f: Fact(name.equals("happy"), answer.equals("So happy she lizzed her parents."))
    then
        new Fact("30Rock");
end

rule "DoctorWho"
    when
        f: Fact(name.equals("pregnant"), answer.equals("What do you mean, 'during'?"))
    then
        new Fact("DoctorWho");
end